# Generated by Django 4.0.4 on 2022-05-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='login2',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='login3',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='text',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='text2',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='title',
            field=models.CharField(default=2, max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='home',
            name='login',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='home',
            name='logo',
            field=models.CharField(max_length=80),
        ),
    ]
